/**
 * Autoencoder Demo
 * Architecture: Encoder (Linear → ReLU → Linear → ReLU → Linear) → Bottleneck → Decoder (Linear → ReLU → Linear → ReLU → Linear → Sigmoid)
 * Based on: models.Autoencoder
 */
import type { DemoNetwork } from '../types';

export const autoencoderDemo: DemoNetwork = {
  id: 'demo-autoencoder',
  name: 'Autoencoder',
  description: 'Encoder-decoder architecture with bottleneck for dimensionality reduction',
  nodes: [
    {
      id: 'input',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'placeholder',
        name: 'x',
        label: 'Input',
        layerType: 'Input',
        outputShape: '[1, 784]',
        color: '#4299e1',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'enc1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'encoder.0',
        target: 'encoder.0',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 128]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 784,
          out_features: 128,
        },
      },
    },
    {
      id: 'enc_relu1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'encoder.1',
        target: 'encoder.1',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 128]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'enc2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'encoder.2',
        target: 'encoder.2',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 64]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 128,
          out_features: 64,
        },
      },
    },
    {
      id: 'enc_relu2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'encoder.3',
        target: 'encoder.3',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 64]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'bottleneck',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'encoder.4',
        target: 'encoder.4',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 32]',
        color: '#f56565',
        args: [],
        kwargs: {
          in_features: 64,
          out_features: 32,
        },
      },
    },
    {
      id: 'dec1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'decoder.0',
        target: 'decoder.0',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 64]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 32,
          out_features: 64,
        },
      },
    },
    {
      id: 'dec_relu1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'decoder.1',
        target: 'decoder.1',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 64]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'dec2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'decoder.2',
        target: 'decoder.2',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 128]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 64,
          out_features: 128,
        },
      },
    },
    {
      id: 'dec_relu2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'decoder.3',
        target: 'decoder.3',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 128]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'dec3',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'decoder.4',
        target: 'decoder.4',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 784]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 128,
          out_features: 784,
        },
      },
    },
    {
      id: 'sigmoid',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'decoder.5',
        target: 'decoder.5',
        label: 'Sigmoid',
        layerType: 'Sigmoid',
        outputShape: '[1, 784]',
        color: '#9f7aea',
        args: [],
        kwargs: {},
      },
    },
  ],
  edges: [
    { id: 'e1', source: 'input', target: 'enc1' },
    { id: 'e2', source: 'enc1', target: 'enc_relu1' },
    { id: 'e3', source: 'enc_relu1', target: 'enc2' },
    { id: 'e4', source: 'enc2', target: 'enc_relu2' },
    { id: 'e5', source: 'enc_relu2', target: 'bottleneck' },
    { id: 'e6', source: 'bottleneck', target: 'dec1' },
    { id: 'e7', source: 'dec1', target: 'dec_relu1' },
    { id: 'e8', source: 'dec_relu1', target: 'dec2' },
    { id: 'e9', source: 'dec2', target: 'dec_relu2' },
    { id: 'e10', source: 'dec_relu2', target: 'dec3' },
    { id: 'e11', source: 'dec3', target: 'sigmoid' },
  ],
};
