/**
 * Deep CNN with BatchNorm Demo - Advanced convolutional network
 * Conv → BN → ReLU → Conv → BN → ReLU → MaxPool → Conv → BN → ReLU → Dropout → Linear
 */
import type { DemoNetwork } from '../types';

export const deepCNNDemo: DemoNetwork = {
  id: 'demo-deep-cnn',
  name: 'Deep CNN with BatchNorm',
  description: 'Deep convolutional network with batch normalization and dropout',
  nodes: [
    {
      id: 'input',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'placeholder',
        name: 'x',
        label: 'Input',
        layerType: 'Input',
        outputShape: '[1, 3, 64, 64]',
        color: '#4299e1',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'conv1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'conv1',
        target: 'conv1',
        label: 'Conv2d',
        layerType: 'Conv2d',
        outputShape: '[1, 32, 64, 64]',
        color: '#48bb78',
        args: [],
        kwargs: {
          in_channels: 3,
          out_channels: 32,
          kernel_size: [3, 3],
          padding: [1, 1],
        },
      },
    },
    {
      id: 'bn1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'bn1',
        target: 'bn1',
        label: 'BatchNorm2d',
        layerType: 'BatchNorm2d',
        outputShape: '[1, 32, 64, 64]',
        color: '#9f7aea',
        args: [],
        kwargs: {
          num_features: 32,
        },
      },
    },
    {
      id: 'relu1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'relu1',
        target: 'relu1',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 32, 64, 64]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'conv2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'conv2',
        target: 'conv2',
        label: 'Conv2d',
        layerType: 'Conv2d',
        outputShape: '[1, 64, 64, 64]',
        color: '#48bb78',
        args: [],
        kwargs: {
          in_channels: 32,
          out_channels: 64,
          kernel_size: [3, 3],
          padding: [1, 1],
        },
      },
    },
    {
      id: 'bn2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'bn2',
        target: 'bn2',
        label: 'BatchNorm2d',
        layerType: 'BatchNorm2d',
        outputShape: '[1, 64, 64, 64]',
        color: '#9f7aea',
        args: [],
        kwargs: {
          num_features: 64,
        },
      },
    },
    {
      id: 'relu2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'relu2',
        target: 'relu2',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 64, 64, 64]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'pool',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'pool',
        target: 'pool',
        label: 'MaxPool2d',
        layerType: 'MaxPool2d',
        outputShape: '[1, 64, 32, 32]',
        color: '#9f7aea',
        args: [],
        kwargs: {
          kernel_size: 2,
          stride: 2,
        },
      },
    },
    {
      id: 'conv3',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'conv3',
        target: 'conv3',
        label: 'Conv2d',
        layerType: 'Conv2d',
        outputShape: '[1, 128, 32, 32]',
        color: '#48bb78',
        args: [],
        kwargs: {
          in_channels: 64,
          out_channels: 128,
          kernel_size: [3, 3],
          padding: [1, 1],
        },
      },
    },
    {
      id: 'bn3',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'bn3',
        target: 'bn3',
        label: 'BatchNorm2d',
        layerType: 'BatchNorm2d',
        outputShape: '[1, 128, 32, 32]',
        color: '#9f7aea',
        args: [],
        kwargs: {
          num_features: 128,
        },
      },
    },
    {
      id: 'relu3',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'relu3',
        target: 'relu3',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 128, 32, 32]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'dropout',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'dropout',
        target: 'dropout',
        label: 'Dropout',
        layerType: 'Dropout',
        outputShape: '[1, 128, 32, 32]',
        color: '#f56565',
        args: [],
        kwargs: {
          p: 0.25,
        },
      },
    },
    {
      id: 'flatten',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'flatten',
        target: 'flatten',
        label: 'Flatten',
        layerType: 'Flatten',
        outputShape: '[1, 131072]',
        color: '#38b2ac',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'fc',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'fc',
        target: 'fc',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 1000]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 131072,
          out_features: 1000,
        },
      },
    },
  ],
  edges: [
    { id: 'e1', source: 'input', target: 'conv1' },
    { id: 'e2', source: 'conv1', target: 'bn1' },
    { id: 'e3', source: 'bn1', target: 'relu1' },
    { id: 'e4', source: 'relu1', target: 'conv2' },
    { id: 'e5', source: 'conv2', target: 'bn2' },
    { id: 'e6', source: 'bn2', target: 'relu2' },
    { id: 'e7', source: 'relu2', target: 'pool' },
    { id: 'e8', source: 'pool', target: 'conv3' },
    { id: 'e9', source: 'conv3', target: 'bn3' },
    { id: 'e10', source: 'bn3', target: 'relu3' },
    { id: 'e11', source: 'relu3', target: 'dropout' },
    { id: 'e12', source: 'dropout', target: 'flatten' },
    { id: 'e13', source: 'flatten', target: 'fc' },
  ],
};
