/**
 * ResNet-like Block Demo - Residual connection
 * Conv → BN → ReLU → Conv → BN → Add → ReLU
 */
import type { DemoNetwork } from '../types';

export const resnetBlockDemo: DemoNetwork = {
  id: 'demo-resnet-block',
  name: 'ResNet Block',
  description: 'A residual block with skip connection',
  nodes: [
    {
      id: 'input',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'placeholder',
        name: 'x',
        label: 'Input',
        layerType: 'Input',
        outputShape: '[1, 64, 32, 32]',
        color: '#4299e1',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'conv1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'conv1',
        target: 'conv1',
        label: 'Conv2d',
        layerType: 'Conv2d',
        outputShape: '[1, 64, 32, 32]',
        color: '#48bb78',
        args: [],
        kwargs: {
          in_channels: 64,
          out_channels: 64,
          kernel_size: [3, 3],
          padding: [1, 1],
        },
      },
    },
    {
      id: 'bn1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'bn1',
        target: 'bn1',
        label: 'BatchNorm2d',
        layerType: 'BatchNorm2d',
        outputShape: '[1, 64, 32, 32]',
        color: '#9f7aea',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'relu1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'relu1',
        target: 'relu1',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 64, 32, 32]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'conv2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'conv2',
        target: 'conv2',
        label: 'Conv2d',
        layerType: 'Conv2d',
        outputShape: '[1, 64, 32, 32]',
        color: '#48bb78',
        args: [],
        kwargs: {
          in_channels: 64,
          out_channels: 64,
          kernel_size: [3, 3],
          padding: [1, 1],
        },
      },
    },
    {
      id: 'bn2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'bn2',
        target: 'bn2',
        label: 'BatchNorm2d',
        layerType: 'BatchNorm2d',
        outputShape: '[1, 64, 32, 32]',
        color: '#9f7aea',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'add',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_function',
        name: 'add',
        target: 'add',
        label: 'Add',
        layerType: 'Add',
        outputShape: '[1, 64, 32, 32]',
        color: '#f56565',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'relu2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'relu2',
        target: 'relu2',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 64, 32, 32]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
  ],
  edges: [
    { id: 'e1', source: 'input', target: 'conv1' },
    { id: 'e2', source: 'conv1', target: 'bn1' },
    { id: 'e3', source: 'bn1', target: 'relu1' },
    { id: 'e4', source: 'relu1', target: 'conv2' },
    { id: 'e5', source: 'conv2', target: 'bn2' },
    { id: 'e6', source: 'input', target: 'add' }, // Skip connection
    { id: 'e7', source: 'bn2', target: 'add' },
    { id: 'e8', source: 'add', target: 'relu2' },
  ],
};
