/**
 * Simple CNN Demo - Based on TestModel
 * Conv2d → ReLU → MaxPool → Conv2d → ReLU → MaxPool → Flatten → Linear → ReLU → Dropout → Linear
 * 
 * NOTE: This is a placeholder. To use actual model data, run:
 *   uv run scripts/generate-demo-networks.py
 * 
 * This will generate JSON files in src/lib/demo-networks/ from the actual models.
 */
import type { DemoNetwork } from '../types';

export const simpleCNNDemo: DemoNetwork = {
  id: 'demo-simple-cnn',
  name: 'Simple CNN',
  description: 'A simple convolutional neural network for image classification',
  nodes: [
    {
      id: 'input',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'placeholder',
        name: 'x',
        label: 'Input',
        layerType: 'Input',
        outputShape: '[1, 3, 32, 32]',
        color: '#4299e1',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'conv1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'conv1',
        target: 'conv1',
        label: 'Conv2d',
        layerType: 'Conv2d',
        outputShape: '[1, 16, 32, 32]',
        color: '#48bb78',
        args: [],
        kwargs: {
          in_channels: 3,
          out_channels: 16,
          kernel_size: [3, 3],
          stride: [1, 1],
          padding: [1, 1],
        },
      },
    },
    {
      id: 'relu1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'relu1',
        target: 'relu1',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 16, 32, 32]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'pool1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'pool1',
        target: 'pool1',
        label: 'MaxPool2d',
        layerType: 'MaxPool2d',
        outputShape: '[1, 16, 16, 16]',
        color: '#9f7aea',
        args: [],
        kwargs: {
          kernel_size: 2,
          stride: 2,
        },
      },
    },
    {
      id: 'conv2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'conv2',
        target: 'conv2',
        label: 'Conv2d',
        layerType: 'Conv2d',
        outputShape: '[1, 32, 16, 16]',
        color: '#48bb78',
        args: [],
        kwargs: {
          in_channels: 16,
          out_channels: 32,
          kernel_size: [3, 3],
          stride: [1, 1],
          padding: [1, 1],
        },
      },
    },
    {
      id: 'relu2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'relu2',
        target: 'relu2',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 32, 16, 16]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'pool2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'pool2',
        target: 'pool2',
        label: 'MaxPool2d',
        layerType: 'MaxPool2d',
        outputShape: '[1, 32, 8, 8]',
        color: '#9f7aea',
        args: [],
        kwargs: {
          kernel_size: 2,
          stride: 2,
        },
      },
    },
    {
      id: 'flatten',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'flatten',
        target: 'flatten',
        label: 'Flatten',
        layerType: 'Flatten',
        outputShape: '[1, 2048]',
        color: '#38b2ac',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'fc1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'fc1',
        target: 'fc1',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 128]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 2048,
          out_features: 128,
        },
      },
    },
    {
      id: 'relu3',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'relu3',
        target: 'relu3',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 128]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'dropout',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'dropout',
        target: 'dropout',
        label: 'Dropout',
        layerType: 'Dropout',
        outputShape: '[1, 128]',
        color: '#f56565',
        args: [],
        kwargs: {
          p: 0.5,
        },
      },
    },
    {
      id: 'fc2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'fc2',
        target: 'fc2',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 10]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 128,
          out_features: 10,
        },
      },
    },
  ],
  edges: [
    { id: 'e1', source: 'input', target: 'conv1' },
    { id: 'e2', source: 'conv1', target: 'relu1' },
    { id: 'e3', source: 'relu1', target: 'pool1' },
    { id: 'e4', source: 'pool1', target: 'conv2' },
    { id: 'e5', source: 'conv2', target: 'relu2' },
    { id: 'e6', source: 'relu2', target: 'pool2' },
    { id: 'e7', source: 'pool2', target: 'flatten' },
    { id: 'e8', source: 'flatten', target: 'fc1' },
    { id: 'e9', source: 'fc1', target: 'relu3' },
    { id: 'e10', source: 'relu3', target: 'dropout' },
    { id: 'e11', source: 'dropout', target: 'fc2' },
  ],
};
