/**
 * Transformer Block Demo
 * Architecture: PositionalEncoding → MultiHeadAttention → LayerNorm → FFN → LayerNorm → Output
 * Based on: models.TransformerBlock
 */
import type { DemoNetwork } from '../types';

export const transformerBlockDemo: DemoNetwork = {
  id: 'demo-transformer',
  name: 'Transformer Block',
  description: 'Multi-head self-attention with positional encoding and feedforward network',
  nodes: [
    {
      id: 'input',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'placeholder',
        name: 'x',
        label: 'Input',
        layerType: 'Input',
        outputShape: '[1, 10, 512]',
        color: '#4299e1',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'pos_encoding',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'pos_encoder',
        target: 'pos_encoder',
        label: 'PositionalEncoding',
        layerType: 'PositionalEncoding',
        outputShape: '[1, 10, 512]',
        color: '#9f7aea',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'q_proj',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'q_linear',
        target: 'attention.q_linear',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 10, 512]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 512,
          out_features: 512,
        },
      },
    },
    {
      id: 'k_proj',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'k_linear',
        target: 'attention.k_linear',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 10, 512]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 512,
          out_features: 512,
        },
      },
    },
    {
      id: 'v_proj',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'v_linear',
        target: 'attention.v_linear',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 10, 512]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 512,
          out_features: 512,
        },
      },
    },
    {
      id: 'attention',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_function',
        name: 'matmul',
        target: 'torch.matmul',
        label: 'MultiHeadAttention',
        layerType: 'MultiHeadAttention',
        outputShape: '[1, 10, 512]',
        color: '#48bb78',
        args: [],
        kwargs: {
          num_heads: 8,
        },
      },
    },
    {
      id: 'out_proj',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'out_linear',
        target: 'attention.out_linear',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 10, 512]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 512,
          out_features: 512,
        },
      },
    },
    {
      id: 'norm1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'norm1',
        target: 'norm1',
        label: 'LayerNorm',
        layerType: 'LayerNorm',
        outputShape: '[1, 10, 512]',
        color: '#9f7aea',
        args: [],
        kwargs: {
          normalized_shape: [512],
        },
      },
    },
    {
      id: 'ffn1',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'ffn.0',
        target: 'ffn.0',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 10, 2048]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 512,
          out_features: 2048,
        },
      },
    },
    {
      id: 'relu',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'ffn.1',
        target: 'ffn.1',
        label: 'ReLU',
        layerType: 'ReLU',
        outputShape: '[1, 10, 2048]',
        color: '#ed8936',
        args: [],
        kwargs: {},
      },
    },
    {
      id: 'ffn2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'ffn.2',
        target: 'ffn.2',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 10, 512]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 2048,
          out_features: 512,
        },
      },
    },
    {
      id: 'norm2',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'norm2',
        target: 'norm2',
        label: 'LayerNorm',
        layerType: 'LayerNorm',
        outputShape: '[1, 10, 512]',
        color: '#9f7aea',
        args: [],
        kwargs: {
          normalized_shape: [512],
        },
      },
    },
    {
      id: 'output',
      type: 'transformer',
      position: { x: 0, y: 0 },
      data: {
        op: 'call_module',
        name: 'fc_out',
        target: 'fc_out',
        label: 'Linear',
        layerType: 'Linear',
        outputShape: '[1, 512]',
        color: '#4299e1',
        args: [],
        kwargs: {
          in_features: 512,
          out_features: 512,
        },
      },
    },
  ],
  edges: [
    { id: 'e1', source: 'input', target: 'pos_encoding' },
    { id: 'e2', source: 'pos_encoding', target: 'q_proj' },
    { id: 'e3', source: 'pos_encoding', target: 'k_proj' },
    { id: 'e4', source: 'pos_encoding', target: 'v_proj' },
    { id: 'e5', source: 'q_proj', target: 'attention' },
    { id: 'e6', source: 'k_proj', target: 'attention' },
    { id: 'e7', source: 'v_proj', target: 'attention' },
    { id: 'e8', source: 'attention', target: 'out_proj' },
    { id: 'e9', source: 'pos_encoding', target: 'norm1' },
    { id: 'e10', source: 'out_proj', target: 'norm1' },
    { id: 'e11', source: 'norm1', target: 'ffn1' },
    { id: 'e12', source: 'ffn1', target: 'relu' },
    { id: 'e13', source: 'relu', target: 'ffn2' },
    { id: 'e14', source: 'norm1', target: 'norm2' },
    { id: 'e15', source: 'ffn2', target: 'norm2' },
    { id: 'e16', source: 'norm2', target: 'output' },
  ],
};
