name: CI
on: [push, pull_request]
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 8 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-workspace.yaml
            visuaml-client/pnpm-lock.yaml
      - name: List files in visuaml-client (for debugging)
        run: ls -la visuaml-client
      - name: Install dependencies (workspace root)
        run: pnpm install --frozen-lockfile
      - name: Lint visuaml-client
        run: pnpm --filter visuaml-client run lint
      - name: Check Prettier formatting in visuaml-client
        run: pnpm --dir visuaml-client exec prettier --check .
      - name: Test visuaml-client
        run: pnpm --filter visuaml-client run test -- --run
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install ruff pytest
      - run: ruff check visuaml-client/backend
      - run: pytest -q visuaml-client/backend/tests 